/** @type {import('stylelint').Config} */
export default {
	extends: ['stylelint-config-recommended-scss', 'stylelint-config-css-modules'],
	plugins: ['stylelint-order', 'stylelint-scss', 'stylelint-prettier'],
	ignoreFiles: ['./node_modules/**/*'],
	rules: {
		'prettier/prettier': true,
		'scss/at-rule-no-unknown': null,
		'scss/at-import-no-partial-leading-underscore': null,
		'no-descending-specificity': null,
		'block-no-empty': null,
		'order/order': ['custom-properties', 'declarations'],
		'order/properties-order': [
			'box-sizing',
			'content',
			'',
			'position',
			'top',
			'bottom',
			'right',
			'left',
			'',
			'display',
			'flex',
			'flex-basis',
			'flex-direction',
			'flex-flow',
			'flex-grow',
			'flex-shrink',
			'flex-wrap',
			'align-content',
			'align-items',
			'align-self',
			'justify-content',
			'grid',
			'grid-template-columns',
			'grid-template-rows',
			'order',
			'gap',
			'',
			'padding',
			'padding-top',
			'padding-right',
			'padding-left',
			'padding-bottom',
			'margin',
			'margin-top',
			'margin-right',
			'margin-left',
			'margin-bottom',
			'',
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'',
			'color',
			'background',
			'',
			'animation',
		],
	},
};
